apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate 
  template: 
    metadata: 
      labels: 
        app: postgres
    spec: 
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
              name: postgres 
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data                                            
      volumes: 
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: ebs-mysql-pv-claim