# Istio VirtualService
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: usermgmt-vs
spec:
  hosts:
  - "*"
  gateways:
  - usermgmt-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: usermgmt-restapp
        port:
          number: 8080