# templates/postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.env.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.env.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.env.db }}
            - name: PGDATA
              value: {{ .Values.postgres.env.pgdata }}
          ports:
            - containerPort: {{ .Values.postgres.servicePort }}
              name: postgres
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.claimName }}
